language: node_js
node_js:
  - lts/*
deploy:
  provider: npm
  email:
    secure: "nRuMNuskhO3lr7nUVhIZvlJOuzf2T0YWANaQXpAyeqd2dP75v1fBm/RxijzK7GkWLEGDU26KJDEdwgc3gC8w3YasP/dyf2qH//CZcyz3Szj/uUodtgbTGKmfGaR7pV15K6iT8PGR0i8A4h0Zfd9QiDbRiY4XM0pvGeg0A1pWRXm8MED5KUv+NgJHLLlr3frtTb6zI/fpr06mJr/L6TFULickdxZXdsxhWTN0WxaWl7ugFAj004e07weLIGHMfaSlCaFwqzisr3nYkXINO54kE+rQHADTpL6s72Hhd+XXObjp44RdUsvVIF9bLKcSNV9D2DQoYQ5cptXoSubSvh6OEXrbeyqH/RMa9VA43fa4g3Dj1wXytDLygEvCI3T+zsKqesYeKUvKPH7wzDRbAM9+qGYnxR2gBIfp7Kaoy9pMzvr+dck4uRXjfkiWu2zJ3hvNMk97c/kPJPRbIBqUo9yb6Bzn/DU4thOwyR1PKKYf+NMoTJScLmkXZ9bTrz9aJ7OqwN5WkmeiIj3Ut7DXC3iG4pJ07O9T4oN4dP89iU7p4lRCBuefjk6V3PuWKvD0qznQl6hbDn/BxJ9MYTYvZRalJI4Y7MKwQKjbd0fZ1QvQ2vuq2saKwpbcgPq7CcIGg9at0wobAq/7dCZ67TiRQKxRDClcy5s1/Yhqh2jpS9NyfgA="
  api_key: # 5976
    secure: "GQQ7ghtHOClwHwXtwtxx2BPDRNOB2K76D692K7gSA3mjyDmDbLXUPO0Cgj4Qol/iI3gOdEsU1j4ODO0Ij5kBOUh4Vt2GwNEvYZm9V7qo6xxoX2mHvdAfUMGd9/sbt98Orr0MECrFn9Wqdqjwa7ekQ5TUhTc4EPMjk5wPYgZXH4WQJka26u1x2jajNal2e3kHDwwggmMmrHIm+/jHJeydWxe0nMZYjV2bnH2VsTBaa5AGCPOvg1GEOMla10LYUYD1FjqrnrRTtFJslwNvbRAwfYesfqgV1C/SO108hAtcjwSABxUIF3lTKypCtdCHoB4JCCQZ1MqYO4kuSHe7WrUK358Qi1N3IU3YJkmd8/Hp9TJ15ZYvNTiJMHil+kr4JNfcBHsj3nzWbcLHAofQEn+rU9wKACm0p1UKhQJ6l5U9OwkaQGScDtD9A36mRhcsHDoABWPB8Vgro7vj64IH+uwZifNrDTgaTFitY2ZkD6l5FJ+eQV37hH/9PdRg3XdVSBM4cJUtoYIFxmBlKFfIZBumn2d/5HJIm+Z+llGOgvGG1VnaMoOypfxN7ZqeWOsedN8aChGYzdSQqB4ApODc1rgfE1v8YVyH2P77X6CHRFCeyKXNI4gG7UzBl/FRxZHAtXryWFvhHpz/JU8Niv9RDIYRw2JtjwjBECvGZX55o0zpLCc="
  on:
    tags: true
    node: lts/*
